### ISSUE TITLE
Objeto aleatorio no caminho

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#1]

**Comment by jardeldyonisio** [comment]
Objeto é escolhido aleatóriamente antes de cada rodada ou é definido um para todas as equipes apenas uma vez?

**Comment by fagnerpimentel** [comment]
Não vejo problema em ser o mesmo para todas as equipes.

**Comment by jardeldyonisio** [comment]
Certo!

Solved 50308d36d52f04581d335119d62595a0f3371335.
