### ISSUE TITLE
Definir quais são os possíveis objetos no caminho

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#12]

**Comment by jardeldyonisio** [comment]
Seria qualquer objeto da lista de objetos ou vamos limitar em algo? Exemplo, tiny objects.

**Comment by fagnerpimentel** [comment]
E acho que o ideal é definir qualquer objeto que atenda a uma altura mínima. Talvez 10 cm seja suficiente.

**Comment by jardeldyonisio** [comment]
Solved f2549720d149c7497acae84808b62526e851d63f.
