### ISSUE TITLE
[NEW] - Adicionar pontuação por desvio de objetos

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#13]
Como vão ter obrigatóriamente objetos no caminho do robô com as novas mudanças, pensei em como ficariam as pontuações considerando isso.

- Teremos pontuação por desviar dos objetos? 
> - Caso tenha pontuação, quanto pontos seriam? 
> > - Pensei em reduzir 50 pontos de chegar no waypoint 1 e 50 de chegar ao waypoint 2, sendo assim, desviar do objeto seriam 100 pontos.

- Qual penalidade? 
> - Pensei que se colidir com o item, deixa de disputar os pontos por desviar do objeto.

- Penalidade conta a partir do momento que encosta no objeto? Qualquer tipo de colisão?

**Comment by jardeldyonisio** [comment]
O que acham @anapatriciamagalhaes, @fagnerpimentel, @khaledhazime e @kriskappel?

**Comment by fagnerpimentel** [comment]
Assim fica que fica legal sim. Sobre a colisão acho que encostar no objeto já é suficiente.

**Comment by jardeldyonisio** [comment]
Solved f2549720d149c7497acae84808b62526e851d63f.
