### ISSUE TITLE
O robô coloca ou solta a sacola na posição final

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#2]

**Comment by jardeldyonisio** [comment]
Seria a opção de o robô soltar posicionando a sacola, simplesmente largar a sacola e pedir para a pessoa pegar a sacola do gripper?

**Comment by fagnerpimentel** [comment]
Colocar no chão ou pedir para a pessoa pegar a sacola ou mesmo saltar na mão da pessoa é aceitável, soltar a sacola no chão independente da altura acho que não é aceitável. Para cada um desses comportamentos precisa ter uma pontuação diferente, ou uma penalidade diferente.

**Comment by jardeldyonisio** [comment]
Certo!
