### ISSUE TITLE
Robô pode pedir pro operador esperar, operador deve esperar por x tempo. Adicionar limite no número de solicitações para parar?

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#21]

**Comment by jardeldyonisio** [comment]
Operador esperar até que o robô dê o comando para seguir?

**Comment by fagnerpimentel** [comment]
Operador deve esperar por um curto período de tempo. Acredito que entre 10 e 15 segundos seja suficiente. O que vocês acham?

**Comment by jardeldyonisio** [comment]
A gente iria monitorar esse tempo ou seria mais com relação ao operador não ficar parado por muito tempo?

**Comment by fagnerpimentel** [comment]
Para ele não ficar parado por muito tempo. Podemos indicar ao operador quando der o tempo.
