### ISSUE TITLE
Carry my Luggage e Navigate and Follow me ficam definidas no livro como dentro e fora da arena?

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#27]
Minha dúvida é se vamos manter da forma que está (acontece dentro e fora da arena), mas nos últimos mundiais tivemos problemas com isso e acabaram sendo inteiramente fora da arena. Em Salvador não tivemos problemas com isso, mas em Goias pode ser que seja um problema. Como deixamos no Rulebook? Atualmente da a entender que é tanto fora quanto dentro, podemos definir que é somente fora ou que PODE ser que aconteça tanto fora quanto dentro.

**Comment by fagnerpimentel** [comment]
Isso é um problema que sempre vai depender das condições da arena em cada ano. O ideal é que se mantenha assim mesmo na regra (acontece dentro e fora). Caso não seja possível, fazemos completamente dentro ou completamente fora. 
Se a intenção for deixar mais claro no livro de regras, podemos dizer da seguinte forma: pode acontecer dentro e/ou fora da arena.

**Comment by jardeldyonisio** [comment]
Certo, a ideia é para ser mais claro que pode acontecer de ser totalmente fora ou totalmente dentro como foi o caso da Navigate em Salvado. Commit feito https://github.com/RoboCupAtHomeLatinAmerica/RuleBook/commit/f01dff72e0162108ed6d6e55ad20605baadded49 https://github.com/RoboCupAtHomeLatinAmerica/RuleBook/commit/f7a816ccdc7368e2f9820c505eff0924636edf1a.
