### ISSUE TITLE
Deve pegar a bag apontada, não vale ponto se pegar a outra

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#3]

**Comment by jardeldyonisio** [comment]
Enquanto estava escrevendo na regra, pensei em colocar que o robô não pode pedir confirmação para o operador se pegou a bolsa certa.

**Comment by fagnerpimentel** [comment]
Eu não vejo problema em pedir confirmação. Me parece um comportamento comum até mesmo para um ser humano pedir esse tipo de confirmação. Entendo que a ideia é evitar pontuação fácil mas acredito que a perda de tempo nesse tipo de interação já é uma penalidade.

**Comment by jardeldyonisio** [comment]
Minha preocupação em o robô pedir para pessoa confirmar é que se ele pegar a bolsa errada, ele sabe que a outra que ele pegar vai estar correta, não precisaria interpretar para qual bolsa a pessoa está apontando. Apenas tentaria pegar qualquer bolsa, se pegar a errada ele irá pega a outra sem identificação de qual foi apontada.

**Comment by fagnerpimentel** [comment]
Então, ao meu ver, nessa tentativa de pegar a bolsa errada, colocar ela de volta no chão, em seguida tentar pegar a bolsa correta, ele iria perder muito tempo, e isso em si já seria uma penalidade.
Por outro lado, acho que podemos deixar claro na regra que o intuito desta tarefa é explorar uma interação não verbal, nesse caso o robô não pode pedir confirmação por voz ou texto.

**Comment by jardeldyonisio** [comment]
Eu fiz uma modificação no commit b051e4db56afd540731a3b488108f522e62dc2a2, o que voce acha?

**Comment by fagnerpimentel** [comment]
Ok

**Comment by jardeldyonisio** [comment]
Solved with b051e4db56afd540731a3b488108f522e62dc2a2 and e5c3d419460d53b75d26f9715f51d5304e17003c.
