### ISSUE TITLE
Definir antes o que é tiny e heavy

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#4]

**Comment by jardeldyonisio** [comment]
Pensei em:

Tiny (considerando tamanho):

- Spoon;
- Fork;
- Knife;
- Cloth;
- Sponge (?);
- Kiwi (?).

Heavy (considerando peso):

- Water;
- Cleaner;
- Ice Tea;
- Tonic 
- Guarana (?);
- Coke (?).

- Tem que incluir todos os itens?
- Tiny é com relação a peso ou tamanho?

**Comment by fagnerpimentel** [comment]
Em relação ao tamanho.

**Comment by jardeldyonisio** [comment]
- Tiny:

> - Spoon;
> - Fork;
> - Knife;
> - Cloth.

- Heavy:

> - Water;
> - Cleaner;
> - Ice Tea;
> - Tonic.

O que acham?

**Comment by fagnerpimentel** [comment]
Os objetos podem mudar dependendo da organização local. Acredito que o melhor seja definirmos as dimensões máximas dos objetos pequenos e o intervalo de peso para os objetos pesados.

**Comment by jardeldyonisio** [comment]
Verdade, não tinha me atentando a isso, vou tentar estipular medidas.

**Comment by jardeldyonisio** [comment]
Tiny poderia ser um objeto com pelo menos uma das medidas menores que 1cm? O que acham @anapatriciamagalhaes, @kriskappel e @khaledhazime? Se for esse o caso, incluiria itens como: talheres, panos e etc.

**Comment by fagnerpimentel** [comment]
Acho que podemos estipular essa medida em termos de centímetros cúbicos. Acredito que 5 cm³ sejam suficientes. Obviamente não vai ter ninguém lá medindo exatamente esses valores, mas podemos ter uma ideia do tamanho máximo que o objeto pode ter. Eu perguntei para o ChatGPT exemplos de objetos com essa medida e ele me deu uma lista de exemplos.

Aqui estão alguns exemplos de objetos com até 5 cm³:

Uma borracha de lápis
Um cubo de gelo
Um botão de camisa
Um pedaço pequeno de papel
Um grampo de cabelo
Uma pequena jóia
Uma moeda de um centavo
Um brinco pequeno
Um chaveiro pequeno
Uma pilha pequena.

Acredito que essa definição se encaixa no que precisamos para a tarefa.

**Comment by jardeldyonisio** [comment]
> Acho que podemos estipular essa medida em termos de centímetros cúbicos. Acredito que 5 cm³ sejam suficientes. Obviamente não vai ter ninguém lá medindo exatamente esses valores, mas podemos ter uma ideia do tamanho máximo que o objeto pode ter. Eu perguntei para o ChatGPT exemplos de objetos com essa medida e ele me deu uma lista de exemplos.
> 
> Aqui estão alguns exemplos de objetos com até 5 cm³:
> 
> Uma borracha de lápis Um cubo de gelo Um botão de camisa Um pedaço pequeno de papel Um grampo de cabelo Uma pequena jóia Uma moeda de um centavo Um brinco pequeno Um chaveiro pequeno Uma pilha pequena.
> 
> Acredito que essa definição se encaixa no que precisamos para a tarefa.

Entendi, vou verificar os possiveis itens com essa medida e colocar na regras a medida que vamos usar como base.

**Comment by jardeldyonisio** [comment]
@fagnerpimentel alguma sugestão na faixa de peso para ser considerado um objeto pesado?

**Comment by fagnerpimentel** [comment]
Minha sugestão é que seja algo entre 0.5kg e 0.8kg.

**Comment by jardeldyonisio** [comment]
> Minha sugestão é que seja algo entre 0.5kg e 0.8kg.

De acordo. Tem alguma sugestão de onde posso adicionar essas informações de tamanho e peso no Rulebook?

**Comment by fagnerpimentel** [comment]
No "Setup -> Objects" no arquivo LARC_CleanUp.tex

**Comment by jardeldyonisio** [comment]
Feito https://github.com/RoboCupAtHomeLatinAmerica/RuleBook/commit/a701f76cec606a1bba17d96d5955de16806a18ba.

**Comment by jardeldyonisio** [comment]
Feito https://github.com/RoboCupAtHomeLatinAmerica/RuleBook/commit/a701f76cec606a1bba17d96d5955de16806a18ba.
