### ISSUE TITLE
Operador deve ir para um cômodo sorteado, operador escolher a posição no cômodo

### ISSUE THREAD

**Issue by jardeldyonisio** [RoboCupAtHomeLatinAmerica/RuleBook#6]

**Comment by jardeldyonisio** [comment]
O sorteio é feito para cada execução ou por rounds? Exemplo, considerando que tem quatro equipes, serão feitos quatro sorteios ou apenas um?

**Comment by fagnerpimentel** [comment]
Acredito que o ideal sejam sorteio por rodada.

**Comment by jardeldyonisio** [comment]
Certo!

Solved b3f291ea60d855d214af82e9002da00daea43aae
