### ISSUE TITLE
colocar mais peso na manipulação

### ISSUE THREAD

**Issue by kriskappel** [RoboCupAtHomeLatinAmerica/RuleBook#8]

**Comment by kriskappel** [comment]
Manter o mesmo peso da prova no geral mas só aumentar o peso da manipulação diminuindo o de detecção? Ou aumentar o peso da prova no geral?

**Comment by fagnerpimentel** [comment]
Eu acho que precisamos aumentar o peso da prova no geral mesmo. Idealmente seria interessante que todas as provas tivessem o mesmo valor final, entretanto algumas provas são claramente mais difíceis que outros então a diferença de pontuações é justificada.

**Comment by kriskappel** [comment]
Ok.
Entao fiz a prova valer 1500, sendo 1100 a manipulação, 400 a detecção com bonus de 100 pra objeto ocluso
